- name: "Create users"
  ansible.builtin.user:
    name: "{{ item.user }}"
    groups: sudo
  loop: "{{ users }}"

- name: "Add SSH keys"
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
  loop: "{{ users }}"
